# Name: Git Hook Automation Installer
# Path: tools/sys/install_hooks.py

"""
Installs, verifies, and manages automated client-side Git hooks for the repository.
Deploys:
  - .git/hooks/pre-commit: Runs 'pytest -m smoke' (< 5s sanity check).
  - .git/hooks/pre-push: Runs the complete test suite ('pytest') prior to GitHub pushes.
"""

from __future__ import annotations

import argparse
import logging
from pathlib import Path
import stat
import sys

SCRIPT_PATH = Path(__file__).resolve()
ROOT_DIR = SCRIPT_PATH.parents[2]
GIT_DIR = ROOT_DIR / ".git"
HOOKS_DIR = GIT_DIR / "hooks"

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("install_hooks")

# POSIX / Git Bash compatible shell script template
PRE_COMMIT_SCRIPT = """#!/bin/sh
# Auto-generated by tools/sys/install_hooks.py
echo "[GIT-HOOK] Running pre-commit smoke tests (-m smoke)..."

python -m pytest -m smoke -q
RESULT=$?

# Exit code 0 = passed; Exit code 5 = zero tests collected matching marker
if [ $RESULT -ne 0 ] && [ $RESULT -ne 5 ]; then
    echo ""
    echo "======================================================================="
    echo "[HOOK BLOCKED] Smoke tests failed. Commit aborted."
    echo "Fix failing assertions or run 'python -m pytest -m smoke' to diagnose."
    echo "======================================================================="
    exit 1
fi

echo "[GIT-HOOK] Smoke tests passed cleanly. Proceeding with commit."
exit 0
"""

PRE_PUSH_SCRIPT = """#!/bin/sh
# Auto-generated by tools/sys/install_hooks.py
echo "[GIT-HOOK] Running comprehensive test suite prior to remote push..."

python -m pytest -q
RESULT=$?

if [ $RESULT -ne 0 ]; then
    echo ""
    echo "======================================================================="
    echo "[HOOK BLOCKED] Test suite failed. Push to remote rejected."
    echo "Run 'python -m pytest' locally to inspect and fix all regressions."
    echo "======================================================================="
    exit 1
fi

echo "[GIT-HOOK] Comprehensive test suite passed. Pushing to remote."
exit 0
"""


def verify_git_repository() -> bool:
    """Verifies that the target directory contains a valid .git repository."""
    if not GIT_DIR.exists() or not GIT_DIR.is_dir():
        logger.error("Git directory not found at: %s", GIT_DIR)
        return False
    return True


def make_executable(path: Path) -> None:
    """Ensures executable bit is set for POSIX and Git Bash environments."""
    current_stat = path.stat().st_mode
    path.chmod(current_stat | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def install_hooks() -> bool:
    """Installs pre-commit and pre-push hook scripts into .git/hooks/."""
    if not verify_git_repository():
        return False

    HOOKS_DIR.mkdir(parents=True, exist_ok=True)

    pre_commit_file = HOOKS_DIR / "pre-commit"
    pre_push_file = HOOKS_DIR / "pre-push"

    logger.info("Writing pre-commit hook to: %s", pre_commit_file.relative_to(ROOT_DIR))
    pre_commit_file.write_text(PRE_COMMIT_SCRIPT, encoding="utf-8")
    make_executable(pre_commit_file)

    logger.info("Writing pre-push hook to: %s", pre_push_file.relative_to(ROOT_DIR))
    pre_push_file.write_text(PRE_PUSH_SCRIPT, encoding="utf-8")
    make_executable(pre_push_file)

    logger.info("[SUCCESS] Automated Git hooks installed successfully.")
    return True


def uninstall_hooks() -> bool:
    """Removes installed pre-commit and pre-push hooks."""
    if not verify_git_repository():
        return False

    for hook_name in ("pre-commit", "pre-push"):
        hook_path = HOOKS_DIR / hook_name
        if hook_path.exists():
            hook_path.unlink()
            logger.info("Removed hook: %s", hook_path.relative_to(ROOT_DIR))
        else:
            logger.info("Hook does not exist: %s", hook_name)

    logger.info("[SUCCESS] Hooks uninstalled.")
    return True


def check_status() -> None:
    """Reports status of repository hook files."""
    if not verify_git_repository():
        return

    print("\n--- Git Hooks Status ---")
    for hook_name in ("pre-commit", "pre-push"):
        hook_path = HOOKS_DIR / hook_name
        status = "INSTALLED (Active)" if hook_path.exists() else "NOT INSTALLED"
        print(f"  {hook_name:<15}: {status}")
    print("------------------------\n")


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="install_hooks.py",
        description="Install and configure automated Git quality gates for the repository."
    )
    parser.add_argument("--uninstall", action="store_true", help="Remove installed Git hooks")
    parser.add_argument("--status", action="store_true", help="Check current hook installation status")

    args = parser.parse_args()

    if args.status:
        check_status()
        return 0

    if args.uninstall:
        success = uninstall_hooks()
        return 0 if success else 1

    success = install_hooks()
    return 0 if success else 1


if __name__ == "__main__":
    sys.exit(main())